version: '3'
services:
  influxdb:
    image: influxdb:latest
    volumes:
      - ./docker/influxdb/data:/var/lib/influxdb
      - ./docker/influxdb/config/:/etc/influxdb/
    ports:
      - '8086:8086'
      - '8082:8082'
    networks:
      - internal-network
    environment:
      INFLUXDB_DB: vmetx
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: password
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
  chronograf:
    image: chronograf:latest
    volumes:
      - ./docker/chronograf/data/:/var/lib/chronograf/
    ports:
      - '8888:8888'
    networks:
      - internal-network
    depends_on:
      - influxdb
networks:
  internal-network:
    driver: bridge
